export const CREATE_ADDRESSES_REQUEST = ' CREATE_ADDRESSES_REQUEST'
export const CREATE_ADDRESSES_SUCCESS = 'CREATE_ADDRESSES_SUCCESS'
export const CREATE_ADDRESSES_FAIL = 'CREATE_ADDRESSES_FAIL'
export const CREATE_ADDRESSES_RESET = "CREATE_ADDRESSES_RESET"

export const MY_ADDRESSES_REQUEST = "MY_ADDRESSES_REQUEST"
export const MY_ADDRESSES_SUCCESS = "MY_ADDRESSES_SUCCESS"
export const MY_ADDRESSES_FAIL = "MY_ADDRESSES_FAIL"

export const UPDATE_ADDRESSES_REQUEST = "UPDATE_ADDRESSES_REQUEST"
export const UPDATE_ADDRESSES_SUCCESS = "UPDATE_ADDRESSES_SUCCESS"
export const UPDATE_ADDRESSES_FAIL = "UPDATE_ADDRESSES_SUCCESS"
export const UPDATE_ADDRESSES_RESET = "UPDATE_ADDRESSES_RESET"

export const DELETE_ADDRESSES_REQUEST = 'DELETE_ADDRESSES_REQUEST'
export const DELETE_ADDRESSES_SUCCESS = 'DELETE_ADDRESSES_SUCCESS'
export const DELETE_ADDRESSES_RESET = 'DELETE_ADDRESSES_RESET'
export const DELETE_ADDRESSES_FAIL = 'DELETE_ADDRESSES_FAIL'

export const ADDRESS_DETAILS_REQUEST = 'ADDRESS_DETAILS_REQUEST'
export const ADDRESS_DETAILS_SUCCESS = 'ADDRESS_DETAILS_SUCCESS'
export const ADDRESS_DETAILS_FAIL = 'ADDRESS_DETAILS_FAIL'



export const CLEAR_ERRORS = "CLEAR_ERRORS"