//CREATE BRAND
export const CREATE_BRANDS_REQUEST = 'CREATE_BRANDS_REQUEST'
export const CREATE_BRANDS_SUCCESS = 'CREATE_BRANDS_SUCCESS'
export const CREATE_BRANDS_FAIL = 'CREATE_BRANDS_FAIL'
export const CREATE_BRANDS_RESET = "CREATE_BRANDS_RESET"

//VIEW ALL BRANDS
export const ALL_BRANDS_REQUEST = 'ALL_BRANDS_REQUEST'
export const ALL_BRANDS_SUCCESS = 'ALL_BRANDS_SUCCESS'
export const ALL_BRANDS_FAIL = 'ALL_BRANDS_FAIL'

//VIEW DETAILS
export const BRAND_DETAILS_REQUEST = 'BRAND_DETAILS_REQUEST'
export const BRAND_DETAILS_SUCCESS = 'BRAND_DETAILS_SUCCESS'
export const BRAND_DETAILS_FAIL = 'BRAND_DETAILS_FAIL'

//UPDATE DETAILS
export const UPDATE_BRANDS_REQUEST = "UPDATE_BRANDS_REQUEST"
export const UPDATE_BRANDS_SUCCESS = "UPDATE_BRANDS_SUCCESS"
export const UPDATE_BRANDS_FAIL = "UPDATE_BRANDS_SUCCESS"
export const UPDATE_BRANDS_RESET = "UPDATE_BRANDS_RESET"

//DELETE BRANDS
export const DELETE_BRANDS_REQUEST = 'DELETE_BRANDS_REQUEST'
export const DELETE_BRANDS_SUCCESS = 'DELETE_BRANDS_SUCCESS'
export const DELETE_BRANDS_RESET = 'DELETE_BRANDS_RESET'
export const DELETE_BRANDS_FAIL = 'DELETE_BRANDS_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS"