//CREATE FUEL
export const CREATE_FUEL_REQUEST = 'CREATE_FUEL_REQUEST'
export const CREATE_FUEL_SUCCESS = 'CREATE_FUEL_SUCCESS'
export const CREATE_FUEL_FAIL = 'CREATE_FUEL_FAIL'
export const CREATE_FUEL_RESET = "CREATE_FUEL_RESET"

//PROFILE FUEL
export const MY_FUEL_REQUEST = "MY_FUEL_REQUEST"
export const MY_FUEL_SUCCESS = "MY_FUEL_SUCCESS"
export const MY_FUEL_FAIL = "MY_FUEL_FAIL"

//VIEW ALL FUEL
export const ALL_FUEL_REQUEST = 'ALL_FUEL_REQUEST'
export const ALL_FUEL_SUCCESS = 'ALL_FUEL_SUCCESS'
export const ALL_FUEL_FAIL = 'ALL_FUEL_FAIL'

//VIEW FUEL DETAILS
export const FUEL_DETAILS_REQUEST = 'FUEL_DETAILS_REQUEST'
export const FUEL_DETAILS_SUCCESS = 'FUEL_DETAILS_SUCCESS'
export const FUEL_DETAILS_FAIL = 'FUEL_DETAILS_FAIL'

//UPDATE FUEL DETAILS
export const UPDATE_FUEL_REQUEST = "UPDATE_FUEL_REQUEST"
export const UPDATE_FUEL_SUCCESS = "UPDATE_FUEL_SUCCESS"
export const UPDATE_FUEL_FAIL = "UPDATE_FUEL_SUCCESS"
export const UPDATE_FUEL_RESET = "UPDATE_FUEL_RESET"

//DELETE FUEL
export const DELETE_FUEL_REQUEST = 'DELETE_FUEL_REQUEST'
export const DELETE_FUEL_SUCCESS = 'DELETE_FUEL_SUCCESS'
export const DELETE_FUEL_RESET = 'DELETE_FUEL_RESET'
export const DELETE_FUEL_FAIL = 'DELETE_FUEL_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS"