export const MY_TASKS_REQUEST = 'MY_TASKS_REQUEST'
export const MY_TASKS_SUCCESS = 'MY_TASKS_SUCCESS'
export const MY_TASKS_FAIL = 'MY_TASKS_FAIL'

export const ALL_REVIEWS_MECHANIC_REQUEST = 'ALL_REVIEWS_MECHANIC_REQUEST'
export const ALL_REVIEWS_MECHANIC_SUCCESS = 'ALL_REVIEWS_MECHANIC_SUCCESS'
export const ALL_REVIEWS_MECHANIC_FAIL = 'ALL_REVIEWS_MECHANIC_FAIL'

export const NEW_MECHANIC_REVIEW_REQUEST = "NEW_MECHANIC_REVIEW_REQUEST";
export const NEW_MECHANIC_REVIEW_SUCCESS = "NEW_MECHANIC_REVIEW_SUCCESS";
export const NEW_MECHANIC_REVIEW_RESET = "NEW_MECHANIC_REVIEW_RESET";
export const NEW_MECHANIC_REVIEW_FAIL = "NEW_MECHANIC_REVIEW_FAIL";

export const CLEAR_ERRORS = 'CLEAR_ERRORS'