//CREATE MOTORCYCLES
export const CREATE_MOTORCYCLES_REQUEST = 'CREATE_MOTORCYCLES_REQUEST'
export const CREATE_MOTORCYCLES_SUCCESS = 'CREATE_MOTORCYCLES_SUCCESS'
export const CREATE_MOTORCYCLES_FAIL = 'CREATE_MOTORCYCLES_FAIL'
export const CREATE_MOTORCYCLES_RESET = "CREATE_MOTORCYCLES_RESET"

//PROFILE MOTORCYLES
export const MY_MOTORCYCLES_REQUEST = "MY_MOTORCYCLES_REQUEST"
export const MY_MOTORCYCLES_SUCCESS = "MY_MOTORCYCLES_SUCCESS"
export const MY_MOTORCYCLES_FAIL = "MY_MOTORCYCLES_FAIL"


//VIEW ALL MOTORCYCLES
export const ALL_MOTORCYCLES_REQUEST = 'ALL_MOTORCYCLES_REQUEST'
export const ALL_MOTORCYCLES_SUCCESS = 'ALL_MOTORCYCLES_SUCCESS'
export const ALL_MOTORCYCLES_FAIL = 'ALL_MOTORCYCLES_FAIL'

//VIEW DETAILS
export const MOTORCYCLE_DETAILS_REQUEST = 'MOTORCYCLE_DETAILS_REQUEST'
export const MOTORCYCLE_DETAILS_SUCCESS = 'MOTORCYCLE_DETAILS_SUCCESS'
export const MOTORCYCLE_DETAILS_FAIL = 'MOTORCYCLE_DETAILS_FAIL'

//UPDATE DETAILS
export const UPDATE_MOTORCYCLES_REQUEST = "UPDATE_MOTORCYCLES_REQUEST"
export const UPDATE_MOTORCYCLES_SUCCESS = "UPDATE_MOTORCYCLES_SUCCESS"
export const UPDATE_MOTORCYCLES_FAIL = "UPDATE_MOTORCYCLES_SUCCESS"
export const UPDATE_MOTORCYCLES_RESET = "UPDATE_MOTORCYCLES_RESET"

//DELETE MOTORCYCLES
export const DELETE_MOTORCYCLES_REQUEST = 'DELETE_MOTORCYCLES_REQUEST'
export const DELETE_MOTORCYCLES_SUCCESS = 'DELETE_MOTORCYCLES_SUCCESS'
export const DELETE_MOTORCYCLES_RESET = 'DELETE_MOTORCYCLES_RESET'
export const DELETE_MOTORCYCLES_FAIL = 'DELETE_MOTORCYCLES_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS"