export const PRICE_HISTORY_REQUEST = 'PRICE_HISTORY_REQUEST'
export const PRICE_HISTORY_SUCCESS = 'PRICE_HISTORY_SUCCESS'
export const PRICE_HISTORY_FAIL = 'PRICE_HISTORY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'