export const PRODUCT_SALES_REQUEST = 'PRODUCT_SALES_REQUEST'
export const PRODUCT_SALES_SUCCESS = 'PRODUCT_SALES_SUCCESS'
export const PRODUCT_SALES_FAIL = 'PRODUCT_SALES_FAIL'

export const MOST_LOYAL_REQUEST = 'MOST_LOYAL_REQUEST'
export const MOST_LOYAL_SUCCESS = 'MOST_LOYAL_SUCCESS'
export const MOST_LOYAL_FAIL = 'MOST_LOYAL_FAIL'

export const MOST_BRAND_REQUEST = 'MOST_BRAND_REQUEST'
export const MOST_BRAND_SUCCESS = 'MOST_BRAND_SUCCESS'
export const MOST_BRAND_FAIL = 'MOST_BRAND_FAIL'

export const MONTHLY_SALES_REQUEST = 'MONTHLY_SALES_REQUEST'
export const MONTHLY_SALES_SUCCESS = 'MONTHLY_SALES_SUCCESS'
export const MONHTLY_SALES_FAIL = 'MONHTLY_SALES_FAIL'

export const MOST_RATED_REQUEST = 'MOST_RATED_REQUEST'
export const MOST_RATED_SUCCESS = 'MOST_RATED_SUCCESS'
export const MOST_RATED_FAIL = 'MOST_RATED_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
