export const STOCK_HISTORY_REQUEST = 'STOCK_HISTORY_REQUEST'
export const STOCK_HISTORY_SUCCESS = 'STOCK_HISTORY_SUCCESS'
export const STOCK_HISTORY_FAIL = 'STOCK_HISTORY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'