export const SUPPLIER_HISTORY_REQUEST = 'SUPPLIER_HISTORY_REQUEST'
export const SUPPLIER_HISTORY_SUCCESS = 'SUPPLIER_HISTORY_SUCCESS'
export const SUPPLIER_HISTORY_FAIL = 'SUPPLIER_HISTORY_FAIL'
export const SUPPLIER_HISTORY_RESET = 'SUPPLIER_HISTORY_RESET'

export const SUPPLIED_DETAILS_REQUEST = 'SUPPLIED_DETAILS_REQUEST'
export const SUPPLIED_DETAILS_SUCCESS = 'SUPPLIED_DETAILS_SUCCESS'
export const SUPPLIED_DETAILS_FAIL = 'SUPPLIED_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'